### ISSUE TITLE
Issue with Window size

### ISSUE THREAD

**Issue by vishalbajp** [VeronicaGeek/O365-Data-Retriever-Tool#12]
I see issue with the Window size. Not getting full display of the console and there is no option to scroll up or sideways. I tried on couple of desktops and servers. Running on PowerShell 5.0. 

![o365](https://user-images.githubusercontent.com/40603057/44484802-488a3380-a63e-11e8-9c3d-71bbdd998d8e.jpg)

**Comment by VeronicaGeek** [comment]
Just to make sure:
- Have you downloaded all the necessary files & folders? (located in the README file)
- What is the display resolution you're using on the desktop(s)?
- Can you try on a brand new VM?

Thanks
